#!/bin/sh

get_config() {
  CONFIG_FILE=/etc/fruit.json
  VALUE=$(JSON.sh < $CONFIG_FILE | grep $1 | cut -f2)
  [ "$VALUE" = "" ] && echo "" || echo $VALUE | xargs printf
}

# Send heart-beat
send_heartbeat() {
  # generate state file
  file=$(mktemp)
  cat > $file <<EOL
{
  "serial":"$(cat /proc/cpuinfo | grep "^Serial" | awk '{print $3}')",
  "revision":"$(cat /proc/cpuinfo | grep "^Revision" | awk '{print $3}')",
  "mode": "slave",
  "master": "$(cat /etc/netboot-master)",
  "network": {
EOL
  count=0
  for dev in $(ip -o link show | cut -d' ' -f2 | sed 's/:$//' | grep -v '^lo$'); do
    [ $count -gt 0 ] && echo ',' >> $file
    cat >> $file <<EOL
    "$dev": {
      "ip": "$(ip -4 addr show dev $dev scope global 2>/dev/null | grep inet | awk '{print $2}' | sed 'N;s/\n/,/')",
      "ip6": "$(ip -6 addr show dev $dev scope global 2>/dev/null | grep inet | awk '{print $2}' | sed 'N;s/\n/,/')"
    }
EOL
    count=$((count + 1))
  done
  cat >> $file <<EOL
  }
}
EOL

  name=$(hostname)
  address=mgmt.fruit-testbed.org
  port=443
  user="fruit-$(uname -n)"
  passwd=$(sha256sum /etc/ssh/ssh_host_rsa_key | cut -d' ' -f1)
  uri="/api/status/$name"
  url="https://${user}:${passwd}@${address}:${port}${uri}"

  curl -f -s -X PUT \
      --connect-timeout 5 \
      -H 'Content-Type: application/json' \
      -H 'Accept: application/json' \
      -d @${file} \
      ${url}

  [ $? -eq 0 ] && logger -t fruit "Heartbeat sent to ${url}." || logger -t fruit "Failed to send a heartbeat."

  rm ${file}
}

send_heartbeat


exit 0
